### ISSUE TITLE
How do I solve RuntimeError: Pass exactly one of: hashes, file_ids

### ISSUE THREAD

**Issue by e7777z777** [rachmadaniHaryono/iqdb_tagger#7]
I am new to hydrus and I have no idea what went wrong, sorry if this is a stupid question. I have 0 knowledge about programming. 

I run this the the cmd prompt:
iqdb-tagger search-hydrus-and-send-tag --access_key my_access_key 'my:tag'

This is what I get:
Traceback (most recent call last):
  File "c:\Python38\Scripts\iqdb-tagger-script.py", line 11, in <module>
    load_entry_point('iqdb-tagger==0.3.1', 'console_scripts', 'iqdb-tagger')()
  File "c:\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python38\lib\site-packages\flask\cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\iqdb_tagger\__main__.py", line 522, in search_hydrus_and_send_tag
    for res_dict in get_hydrus_set(search_tags, cl):
  File "c:\python38\lib\site-packages\iqdb_tagger\__main__.py", line 468, in get_hydrus_set
    metadata_sets = cl.file_metadata(file_ids=file_ids, only_identifiers=True)
  File "c:\python38\lib\site-packages\hydrus\__init__.py", line 499, in file_metadata
    raise RuntimeError("Pass exactly one of: hashes, file_ids")

**Comment by rachmadaniHaryono** [comment]
it is actually have been fixed by https://github.com/rachmadaniHaryono/iqdb_tagger/commit/95622bc58e6a6d847ce1a7fc418673163c05d067

i'm in process of rewriting the program, so master branch & pypi may not be updated for some time

in the meantime you can install from dev branch using pip

guide for pip installation https://stackoverflow.com/a/4921215

and then run 

```sh
pip install https://github.com/rachmadaniHaryono/iqdb_tagger/archive/dev.zip
```

**Comment by e7777z777** [comment]
Thank you! I fixed the error message.

This is what I did:
pip uninstall hydrus-api
pip uninstall iqdb_tagger
pip --use-feature=2020-resolver install https://github.com/rachmadaniHaryono/iqdb_tagger/archive/dev.zip
iqdb-tagger search-hydrus-and-send-tag --access_key my_access_key

Now the program run smoothly(still running rn with only 300 image), thanks again!
